#!/usr/bin/env python3
"""
conserve_agg.py — IDIOM #2 for the conservation engine: per-function AGGREGATE<->COLLECTION
delta conservation.

Reads a contract's structure (no test/answer-key) and finds a conservation-partner pair:
  - an aggregate uint  A  (name contains 'total' or 'supply', not constant)
  - a collection       m  (mapping(address => uint256))
that are confirmed partners by a CREDIT function writing BOTH `A +=` and `m[..] +=`.
Then for each DEBIT function (writes `m[..] -=`), it AUTO-EMITS the law:
        Δ A  ==  Δ m[caller]
i.e. the aggregate must move by exactly the amount the constituent moves. A debit that updates the
balance but forgets the aggregate (the classic "burn forgets totalSupply" desync) violates it.

No human writes the invariant — derived from the partner structure. Usage:
  conserve_agg.py <contract.sol> <ContractName>
"""
import re, sys
from pathlib import Path

def strip(s):
    s = re.sub(r"//[^\n]*", "", s); return re.sub(r"/\*.*?\*/", "", s, flags=re.S)

def funcs(src):
    out = {}
    # `[^{};]*` (not `[^{]*`): excludes `;`-terminated interface/abstract method declarations,
    # which otherwise mis-match as a definition whose "body" is the whole contract interior.
    for m in re.finditer(r"function\s+(\w+)\s*\(([^)]*)\)[^{};]*\{", src):
        i = m.end() - 1; depth = 0
        for j in range(i, len(src)):
            if src[j] == "{": depth += 1
            elif src[j] == "}":
                depth -= 1
                if depth == 0: out[m.group(1)] = (m.group(2), src[i+1:j]); break
    return out

def analyze(src):
    src = strip(src)
    # aggregate uint A: a uint256 state var with total/supply in its name, not constant
    aggs = [m.group(1) for m in re.finditer(r"uint256\s+(?:public|private|internal)?\s*(\w*(?:total|supply|Total|Supply)\w*)\s*;", src)]
    maps = [m.group(1) for m in re.finditer(r"mapping\s*\(\s*address\s*=>\s*uint256\s*\)\s*(?:public|private|internal)?\s*(\w+)\s*;", src)]
    fns = funcs(src)
    pair = credit = None
    for A in aggs:
        for m in maps:
            for name, (params, body) in fns.items():
                if re.search(rf"\b{A}\s*\+=", body) and re.search(rf"\b{m}\s*\[[^\]]+\]\s*\+=", body):
                    pair = (A, m); credit = (name, params); break
            if pair: break
        if pair: break
    debits = []
    if pair:
        A, m = pair
        for name, (params, body) in fns.items():
            if re.search(rf"\b{m}\s*\[[^\]]+\]\s*-=", body):
                debits.append((name, params))
    return {"aggs": aggs, "maps": maps, "pair": pair, "credit": credit, "debits": debits}

def call(fnname, params):
    """emit a Solidity call for fn(params): 1 uint param -> prank+call(amt); (address,uint) -> call(USER,amt)."""
    ptypes = [p.strip().split()[0] for p in params.split(",") if p.strip()]
    if ptypes == ["uint256"]:        return f"vm.prank(USER); c.{fnname}(amt);"
    if ptypes[:2] == ["address", "uint256"]: return f"c.{fnname}(USER, amt);"
    if not ptypes:                   return f"vm.prank(USER); c.{fnname}();"
    return f"c.{fnname}(USER, amt); // best-effort"

TEMPLATE = '''// SPDX-License-Identifier: MIT
// AUTO-GENERATED by conserve_agg.py — idiom #2 (aggregate<->collection delta conservation).
pragma solidity ^0.8.20;
import {{Test}} from "forge-std/Test.sol";
import {{{contract}}} from "../{contract}.sol";

contract AutoAggConservation is Test {{
    {contract} c;
    address constant USER = address(0xBEEF);
    function setUp() public {{ c = new {contract}(); }}

    // PROPOSED INVARIANT: in {debit}(), Δ{A} == Δ{m}[caller] (aggregate moves with its constituent)
    function check_autoAggDelta(uint256 amt) public {{
        vm.assume(amt > 0);
        vm.assume(amt < type(uint96).max);
        {setup}                                  // credit USER so the debit has something to move
        int256 A0 = int256(c.{A}());
        int256 m0 = int256(c.{m}(USER));
        {debit_call}
        int256 A1 = int256(c.{A}());
        int256 m1 = int256(c.{m}(USER));
        assert(A1 - A0 == m1 - m0);
    }}
}}
'''

if __name__ == "__main__":
    path, contract = sys.argv[1], sys.argv[2]
    a = analyze(Path(path).read_text())
    print("=== STRUCTURAL ANALYSIS (idiom #2) ===")
    print("aggregates:", a["aggs"], "| collections:", a["maps"])
    if not a["pair"]:
        print("no aggregate<->collection partner pair — idiom #2 declines"); sys.exit(2)
    A, m = a["pair"]
    print(f"PARTNER PAIR: {A} <-> {m}  (confirmed by credit fn {a['credit'][0]} writing both +=)")
    if not a["debits"]:
        print("partner pair found but no debit function — nothing to check"); sys.exit(2)
    debit, dparams = a["debits"][0]
    print(f"DEBIT under test: {debit}({dparams})")
    print(f"\n=== PROPOSED INVARIANT ===\n  in {debit}(): Δ{A} == Δ{m}[caller]")
    setup = call(a["credit"][0], a["credit"][1])
    debit_call = call(debit, dparams)
    out = TEMPLATE.format(contract=contract, A=A, m=m, debit=debit, setup=setup, debit_call=debit_call)
    dest = Path(path).parent / "test" / "AutoAggConservation.t.sol"
    dest.write_text(out)
    print(f"\n=== EMITTED -> {dest} ===")
