#!/usr/bin/env python3
"""
conserve.py — SVM for the load-bearing-graph hypothesis.

Reads a Solidity contract's STRUCTURE (not any hand-written test), detects a
deposit/withdraw (a.k.a. mint/redeem) inverse-operation pair over an external
ERC20 asset, and AUTO-EMITS a round-trip conservation property as a halmos test.

The only inference is structural:
  - a function that does `asset.transferFrom(sender, this, A)` AND `_mint(sender, ...)`
    is a DEPOSIT (value of `asset` flows in, shares minted)
  - a function that does `_burn(sender, ...)` AND `asset.transfer(sender|to, B)`
    is a WITHDRAW (shares burned, value of `asset` flows out)
  - an inverse pair over the same asset must ROUND-TRIP CONSERVE that asset:
        withdraw(deposit(x))  must not return MORE asset than x.
That conservation law is the proposed invariant. halmos discharges it.

No human wrote "redeem should return the deposit." The tool derived it from the
in/out structure. Usage: conserve.py <contract.sol> <ContractName>
"""
import re, sys, json
from pathlib import Path

def strip_comments(s):
    s = re.sub(r"//[^\n]*", "", s)
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    return s

def functions(src):
    """Return {name: body} for each external/public function.

    The gap between `)` and the opening `{` must contain no `;` or `}`: that excludes
    `;`-terminated *declarations* (interface / abstract method signatures), which otherwise
    get mis-matched as definitions whose brace-matched "body" is the whole contract interior
    — a phantom function that fuses every in/out op into a spurious deposit/withdraw pair.
    """
    out = {}
    for m in re.finditer(r"function\s+(\w+)\s*\(([^)]*)\)[^{};]*\{", src):
        name, params = m.group(1), m.group(2)
        # brace-match the body
        i = m.end() - 1; depth = 0
        for j in range(i, len(src)):
            if src[j] == "{": depth += 1
            elif src[j] == "}":
                depth -= 1
                if depth == 0:
                    out[name] = (params, src[i+1:j]); break
    return out

def analyze(src):
    src = strip_comments(src)
    fns = functions(src)
    asset = None
    deposits, withdraws = [], []
    for name, (params, body) in fns.items():
        # external asset moved IN: <asset>.transferFrom(..., address(this), <amt>)
        m_in  = re.search(r"(\w+)\.transferFrom\([^,]+,\s*address\(this\)\s*,\s*([^)]+)\)", body)
        # external asset moved OUT: <asset>.transfer(<to>, <amt>)
        m_out = re.search(r"(\w+)\.transfer\(([^,]+),\s*([^)]+)\)", body)
        mints = re.search(r"_mint\(", body)
        burns = re.search(r"_burn\(", body)
        if m_in and mints:
            asset = asset or m_in.group(1)
            deposits.append({"fn": name, "param": params.split()[-1] if params else "amount",
                             "asset": m_in.group(1), "in_amt": m_in.group(2).strip()})
        if burns and m_out:
            asset = asset or m_out.group(1)
            withdraws.append({"fn": name, "param": params.split()[-1] if params else "amount",
                              "asset": m_out.group(1), "out_amt": m_out.group(3).strip()})
    pair = None
    for d in deposits:
        for w in withdraws:
            if d["asset"] == w["asset"]:
                pair = {"deposit": d, "withdraw": w, "asset": d["asset"]}
    return {"functions": list(fns), "deposits": deposits, "withdraws": withdraws, "pair": pair}

TEMPLATE = '''// SPDX-License-Identifier: MIT
// AUTO-GENERATED by conserve.py from the contract's deposit/withdraw structure.
// NO human authored this property; it was inferred from an inverse-op pair over {asset}.
pragma solidity ^0.8.20;

import {{Test}} from "forge-std/Test.sol";
import {{{contract}}} from "../{contract}.sol";

contract MockUSDC {{
    mapping(address => uint256) public balanceOf;
    function transferFrom(address f, address t, uint256 a) external returns (bool) {{ balanceOf[f]-=a; balanceOf[t]+=a; return true; }}
    function transfer(address t, uint256 a) external returns (bool) {{ balanceOf[msg.sender]-=a; balanceOf[t]+=a; return true; }}
    function mintTo(address t, uint256 a) external {{ balanceOf[t]+=a; }}
}}

contract AutoConservation is Test {{
    {contract} c;
    MockUSDC asset;
    address constant USER = address(0xBEEF);

    function setUp() public {{
        asset = new MockUSDC();
        c = new {contract}(address(asset));
        asset.mintTo(address(c), 1e30); // deep reserve so a buggy withdraw doesn't underflow-revert (vacuous pass)
    }}

    // PROPOSED INVARIANT (structural): {english}
    function check_autoRoundTripConserves(uint256 x) public {{
        vm.assume(x > 0);
        vm.assume(x < type(uint96).max);
        asset.mintTo(USER, x);
        vm.startPrank(USER);
        c.{deposit_fn}(x);
        uint256 shares = c.balanceOf(USER);
        uint256 before = asset.balanceOf(USER);
        c.{withdraw_fn}(shares);
        uint256 afterBal = asset.balanceOf(USER);
        vm.stopPrank();
        // round-trip must not MINT external value from nothing
        assert(afterBal - before <= x);
    }}
}}
'''

if __name__ == "__main__":
    path, contract = sys.argv[1], sys.argv[2]
    src = Path(path).read_text()
    a = analyze(src)
    print("=== STRUCTURAL ANALYSIS (no test/answer-key read) ===")
    print("functions:", a["functions"])
    for d in a["deposits"]:  print(f"  DEPOSIT  {d['fn']}: {d['asset']}.transferFrom in ({d['in_amt']}) + _mint")
    for w in a["withdraws"]: print(f"  WITHDRAW {w['fn']}: _burn + {w['asset']}.transfer out ({w['out_amt']})")
    if not a["pair"]:
        print("no deposit/withdraw inverse pair found — no conservation invariant proposed"); sys.exit(2)
    p = a["pair"]
    english = (f"a {p['deposit']['fn']}(x) -> {p['withdraw']['fn']}() round-trip must not return "
               f"more {p['asset']} than x (no value minted from nothing)")
    print("\n=== PROPOSED CONSERVATION INVARIANT ===\n ", english)
    out = TEMPLATE.format(contract=contract, asset=p["asset"], english=english,
                          deposit_fn=p["deposit"]["fn"], withdraw_fn=p["withdraw"]["fn"])
    dest = Path(path).parent / "test" / "AutoConservation.t.sol"
    dest.write_text(out)
    print(f"\n=== EMITTED halmos test -> {dest} ===")
'''  '''
